import { keyLesson } from "../key-lesson";
import type { CurriculumUnitSource } from "../types";

export const fingerAnchorsUnit = {
  id: "foundation-u01-finger-anchors",
  track: "foundation",
  title: "Build the finger anchors",
  lessons: [
    keyLesson({
      id: "foundation-u01-key-r-ma",
      output: "မ",
      keyLabel: "R · left index",
      title: "Learn မ on R",
    }),
    keyLesson({
      id: "foundation-u01-key-t-a",
      output: "အ",
      keyLabel: "T · left index",
      title: "Learn အ on T",
      practice: ["မ အ မ အ မ အ"],
    }),
    keyLesson({
      id: "foundation-u01-key-y-pa",
      output: "ပ",
      keyLabel: "Y · right index",
      title: "Learn ပ on Y",
      practice: ["မ ပ အ ပ မ ပ"],
    }),
    keyLesson({
      id: "foundation-u01-key-u-ka",
      output: "က",
      keyLabel: "U · right index",
      title: "Learn က on U",
      practice: ["ပ က မ က အ က"],
    }),
    {
      id: "foundation-u01-index-top-review",
      kind: "drill",
      title: "Index top consonants (R T Y U)",
      hint: "မ အ ပ က · Learn each key before forming syllables",
      lines: [
        "မ အ ပ က မ အ ပ က",
        "မ မ အ အ ပ ပ က က",
        "မ အ မ အ ပ က ပ က",
        "က ပ အ မ မ အ ပ က",
      ],
    },
    keyLesson({
      id: "foundation-u01-key-v-la",
      output: "လ",
      keyLabel: "V · left index",
      title: "Learn လ on V",
      practice: ["မ လ အ လ ပ လ"],
    }),
    keyLesson({
      id: "foundation-u01-key-b-ba",
      output: "ဘ",
      keyLabel: "B · left index",
      title: "Learn ဘ on B",
      practice: ["လ ဘ မ ဘ အ ဘ"],
    }),
    keyLesson({
      id: "foundation-u01-key-n-nya",
      output: "ည",
      keyLabel: "N · right index",
      title: "Learn ည on N",
      practice: ["ဘ ည လ ည က ည"],
    }),
    {
      id: "foundation-u01-index-bottom-review",
      kind: "drill",
      title: "Index bottom consonants (V B N)",
      hint: "လ ဘ ည · Reach down from the F and J bumps",
      lines: ["လ ဘ ည လ ဘ ည", "လ လ ဘ ဘ ည ည", "မ လ အ ဘ ပ ည က လ", "ည ဘ လ က ပ အ မ"],
    },
    keyLesson({
      id: "foundation-u01-key-e-na",
      output: "န",
      keyLabel: "E · left middle",
      title: "Learn န on E",
      practice: ["မ န ပ န က န"],
    }),
    keyLesson({
      id: "foundation-u01-key-c-kha",
      output: "ခ",
      keyLabel: "C · left middle",
      title: "Learn ခ on C",
      practice: ["န ခ မ ခ လ ခ"],
    }),
    keyLesson({
      id: "foundation-u01-key-i-nga",
      output: "င",
      keyLabel: "I · right middle",
      title: "Learn င on I",
      practice: ["ခ င န င က င"],
    }),
    {
      id: "foundation-u01-middle-review",
      kind: "drill",
      title: "Middle consonants (E C I)",
      hint: "န ခ င · Match each vertical middle-finger reach",
      lines: ["န ခ င န ခ င", "န န ခ ခ င င", "မ န ပ ခ က င လ န", "င ခ န လ က ပ မ"],
    },
    keyLesson({
      id: "foundation-u01-key-w-ta",
      output: "တ",
      keyLabel: "W · left ring",
      title: "Learn တ on W",
      practice: ["မ တ န တ လ တ"],
    }),
    keyLesson({
      id: "foundation-u01-key-x-hta",
      output: "ထ",
      keyLabel: "X · left ring",
      title: "Learn ထ on X",
      practice: ["တ ထ န ထ က ထ"],
    }),
    keyLesson({
      id: "foundation-u01-key-o-tha",
      output: "သ",
      keyLabel: "O · right ring",
      title: "Learn သ on O",
      practice: ["ထ သ တ သ င သ"],
    }),
    {
      id: "foundation-u01-ring-review",
      kind: "drill",
      title: "Ring consonants (W X O)",
      hint: "တ ထ သ · Match each vertical ring-finger reach",
      lines: ["တ ထ သ တ ထ သ", "တ တ ထ ထ သ သ", "မ တ ပ ထ က သ လ တ", "သ ထ တ န ခ င က"],
    },
  ],
} satisfies CurriculumUnitSource;
